---
apiVersion: v2
name: tssc-tas
description: Red Hat Trusted Artifact Signer
type: application
version: "1.8.0"
appVersion: "1.3"
annotations:
  helmet.redhat-appstudio.github.com/product-name: Trusted Artifact Signer
  helmet.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions, tssc-infrastructure, tssc-iam
  helmet.redhat-appstudio.github.com/integrations-provided: tas
