---
trustedArtifactSigner:
  # OpenShift cluster's ingress domain, e.g. apps.cluster.example.com. The domain
  # is used to generate the "trusted-artifact-signer" Fulcio's email.
  ingressDomain: __OVERWRITE_ME__
  # Configures the Trusted Artifact Signer.
  secureSign:
    # Enable the Trusted Artifact Signer.
    enabled: true
    # Kubernetes namespace and name of the Trusted Artifact Signer.
    namespace: __OVERWRITE_ME__
    # Kubernetes instance name.
    name: trusted-artifact-signer
    # Fulcio configuration.
    fulcio:
      # Fulcio's OIDC configuration.
      oidc:
        # Keycloak's realm URL.
        issuerURL: __OVERWRITE_ME__
        # "trusted-artifact-signer" client "secret-id".
        clientID: trusted-artifact-signer
      # Fulcio's certificate configuration.
      certificate:
        # Fulcio's certificate's common name.
        commonName: fulcio.hostname
        # Fulcio's certificate's organization name.
        organizationName: __OVERWRITE_ME__
  integrationSecret:
    namespace: __OVERWRITE_ME__
