---
apiVersion: v2
name: tssc-konflux
description: TSSC Konflux
type: application
version: "1.6.0"
appVersion: "0.0"
annotations:
  tssc.redhat-appstudio.github.com/product-name: Konflux
  tssc.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions