---
apiVersion: v2
name: tssc-pipelines
description: TSSC OpenShift Pipelines
type: application
version: "1.8.0"
appVersion: "1.20"
annotations:
  helmet.redhat-appstudio.github.com/product-name: OpenShift Pipelines
  helmet.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions
  helmet.redhat-appstudio.github.com/integrations-required: tas
