apiVersion: v2
name: tssc-app-namespaces
description: Red Hat User Application Namespaces
type: application
version: "1.8.0"
annotations:
  helmet.redhat-appstudio.github.com/depends-on: tssc-acs, tssc-pipelines, tssc-tpa
  helmet.redhat-appstudio.github.com/integrations-required: "(bitbucket || github || gitlab) && acs && trustification"
