---
apiVersion: v2
name: tssc-integrations
description: TSSC Integrations
type: application
version: "1.8.0"
annotations:
  helmet.redhat-appstudio.github.com/depends-on: tssc-acs, tssc-gitops, tssc-dh
