---
apiVersion: v2
name: tssc-acs-test
description: TSSC Advanced Cluster Security Test
type: application
version: "1.8.0"
appVersion: "4.8"
annotations:
  helmet.redhat-appstudio.github.com/use-product-namespace: Advanced Cluster Security
  helmet.redhat-appstudio.github.com/depends-on: tssc-acs
  helmet.redhat-appstudio.github.com/weight: "99"
