apiVersion: v2
name: tssc-dh
description: Red Hat Developer Hub
type: application
version: "1.8.0"
appVersion: "1.8"
annotations:
  helmet.redhat-appstudio.github.com/product-name: Developer Hub
  helmet.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions, tssc-infrastructure, tssc-gitops, tssc-pipelines, tssc-app-namespaces
  helmet.redhat-appstudio.github.com/integrations-required: "(bitbucket || github || gitlab) && (artifactory || nexus || quay)"
