---
debug:
  ci: false

developerHub:
  instanceName: developer-hub
  catalogURL: __OVERWRITE_ME__
  ingressDomain: __OVERWRITE_ME__
  integrationSecrets:
    namespace: __OVERWRITE_ME__
  RBAC:
    adminUsers: __OVERWRITE_ME__
    enabled: __OVERWRITE_ME__
    orgs: __OVERWRITE_ME__
  oidc:
    clientID: __OVERWRITE_ME__
    metadataURL: __OVERWRITE_ME__
    baseURL: __OVERWRITE_ME__
    loginRealm: __OVERWRITE_ME__
    realm: __OVERWRITE_ME__
