---
apiVersion: v2
name: tssc-gitops
description: TSSC OpenShift GitOps
type: application
version: "1.8.0"
appVersion: "1.19"
annotations:
  helmet.redhat-appstudio.github.com/product-name: OpenShift GitOps
  helmet.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions
