{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "tssc-tas-integration") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
  {{- range .Values.appNamespaces.namespace_prefixes }}
    {{- $namespace := . }}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: tas-secret
  namespace: {{ $namespace }}-ci
data:
  rekor_url: {{ $secretData.rekor_url }}
  tuf_url:  {{ $secretData.tuf_url }}
  {{- end }}
{{- end }}