---
apiVersion: v2
name: tssc-quay
description: TSSC Quay
type: application
version: "1.6.0"
appVersion: "3.14"
annotations:
  tssc.redhat-appstudio.github.com/product-name: Quay
  tssc.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions, tssc-odf