---
apiVersion: v2
name: tssc-acs
description: TSSC Advanced Cluster Security
type: application
version: "1.8.0"
appVersion: "4.8"
annotations:
  helmet.redhat-appstudio.github.com/product-name: Advanced Cluster Security
  helmet.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions
  helmet.redhat-appstudio.github.com/integrations-provided: acs
