---
apiVersion: v2
name: tssc-tpa
description: TSSC Trusted Profile Analyzer
type: application
version: "1.7.0"
appVersion: "2.1.0"
annotations:
  tssc.redhat-appstudio.github.com/product-name: Trusted Profile Analyzer
  tssc.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions, tssc-infrastructure, tssc-iam
  tssc.redhat-appstudio.github.com/integrations-provided: trustification
