---
apiVersion: v2
name: tssc-tpa
description: TSSC Trusted Profile Analyzer
type: application
version: "1.8.0"
appVersion: "2.2.0"
annotations:
  helmet.redhat-appstudio.github.com/product-name: Trusted Profile Analyzer
  helmet.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions, tssc-infrastructure, tssc-iam
  helmet.redhat-appstudio.github.com/integrations-provided: trustification
