---
apiVersion: v2
name: tssc-cert-manager
description: TSSC Cert-Manager
type: application
version: "1.8.0"
appVersion: "1.x"
annotations:
  tssc.redhat-appstudio.github.com/product-name: Cert-Manager
  tssc.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions
