kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: tssc-tas-integration
  namespace: {{ .Values.trustedArtifactSigner.integrationSecret.namespace }}
stringData:
  fulcio_service_url: http://fulcio-server.{{ .Release.Namespace }}.svc.cluster.local
  fulcio_url: https://fulcio-server-{{ .Release.Namespace }}.{{ .Values.trustedArtifactSigner.ingressDomain }}
  rekor_service_url: http://rekor-server.{{ .Release.Namespace }}.svc.cluster.local
  rekor_url: https://rekor-server-{{ .Release.Namespace }}.{{ .Values.trustedArtifactSigner.ingressDomain }}
  tuf_service_url: http://tuf.{{ .Release.Namespace }}.svc.cluster.local
  tuf_url: https://tuf-{{ .Release.Namespace }}.{{ .Values.trustedArtifactSigner.ingressDomain }}
