---
tssc:
  settings:
    # Toggles the CRC settings for the installer, which adapts the deployment to
    # work on a CRC development environment.
    crc: false
    # CI/CD settings for the installer workflows.
    ci:
      # Enables installer verbose logging messages for troubleshooting issues.
      debug: false
  products:
    # Red Hat cert-manager Operator provides application certificate lifecycle
    # management.
    - name: Cert-Manager
      enabled: true
      # Uses the installer's namespace.
      properties:
        manageSubscription: true
    # Red Hat Trusted Artifact Signer (TAS) enhances software supply chain
    # security by simplifying cryptographic signing and verification of software
    # artifacts like container images, binaries, and documents, leveraging an
    # OpenID Connect (OIDC) provider such as Keycloak for identity-based signing.
    - name: Trusted Artifact Signer
      enabled: true
      namespace: tssc-tas
      properties:
        manageSubscription: true
    # Red Hat OpenShift Pipelines is a cloud-native CI/CD (Continuous
    # Integration/Continuous Delivery) solution built on Tekton that automates
    # application delivery and reduces time to market on Red Hat OpenShift.
    - name: OpenShift Pipelines
      enabled: true
      # Uses the installer's namespace.
      properties:
        manageSubscription: true
    # Community Konflux Operator  provides the CRDs for the Trusted Software Factory
    # platform.
    - name: Konflux
      enabled: true
      namespace: konflux-ui
      properties:
        manageSubscription: true
    # Red Hat Trusted Profile Analyzer (TPA), which leverages the community-driven
    # Trustification project, helps organizations manage their software supply
    # chain's security by analyzing Software Bills of Materials (SBOMs), vendor
    # Vulnerability Exploitability eXchange (VEX), and Common Vulnerabilities and
    # Exposures (CVE) to assess their risk profile.
    - name: Trusted Profile Analyzer
      enabled: true
      namespace: tssc-tpa
      properties:
        manageSubscription: true
